name: API CI

"on":
  push:
    paths:
      - "watch-wise-api/**"
  pull_request:
    paths:
      - "watch-wise-api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current
      - name: Build with Gradle
        run: gradle clean build
